name: aoc
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8, < 3.10
  - pip
  - go
  - pip:
    - matplotlib
    - numpy
    - scipy
    - sklearn
    - tqdm
    - nose
    - pyyaml
    